<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1521142471444' stop='1521142503090'>
    <name>To test the Angular login functionality</name>
    <title>To test the Angular login functionality</title>
    <test-cases>
        <test-case start='1521142471444' status='failed' stop='1521142501447'>
            <name>Should be able to login registration form successfully and logout</name>
            <title>Should be able to login registration form successfully and logout</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: Wait timed out after 10007ms</message>
                <stack-trace>TimeoutError: Wait timed out after 10007ms
                    at WebDriverError (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
                    at TimeoutError (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\error.js:262:5)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2201:17
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:109:7)
                From: Task: &lt;anonymous wait>
                    at scheduleWait (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2188:20)
                    at ControlFlow.wait (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2517:12)
                    at thenableWebDriverProxy.wait (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
                    at run (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\browser.js:59:33)
                    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\browser.js:67:16)
                    at UserContext.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:15:11)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:95:18)
                From: Task: Run it("Should be able to login registration form successfully and logout") in control flow
                    at UserContext.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:94:19)
                    at attempt (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:64:48
                    at ControlFlow.emit (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
                    at ControlFlow.shutdown_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)
                    at shutdownTask_.MicroTask (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:12:2)
                    at addSpecsToSuite (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:4:1)
                    at Module._compile (module.js:570:32)
                    at Object.Module._extensions..js (module.js:579:10)
                    at Module.load (module.js:487:32)
                    at tryModuleLoad (module.js:446:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1521142501448' status='failed' stop='1521142503089'>
            <name>Should be display error message when invalid login cradentials are entered</name>
            <title>Should be display error message when invalid login cradentials are entered</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='6a3a4a06-5362-4976-9015-3e9c76d3196f-attachment.png' type='image/png' size='6058'/>
            </attachments>
            <failure>
                <message>Failed: No element found using locator: By(css selector, *[id="username"])</message>
                <stack-trace>NoSuchElementError: No element found using locator: By(css selector, *[id="username"])
                    at WebDriverError (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
                    at NoSuchElementError (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\error.js:192:5)
                    at elementArrayFinder.getWebElements.then (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\element.js:814:27)
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:109:7)Error
                    at ElementArrayFinder.applyAction_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.(anonymous function) [as sendKeys] (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.(anonymous function) [as sendKeys] (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\protractor\built\element.js:831:22)
                    at UserContext.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:33:30)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                From: Task: Run it("Should be display error message when invalid login cradentials are entered") in control flow
                    at UserContext.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:94:19)
                    at attempt (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasminewd2\index.js:64:48
                    at ControlFlow.emit (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
                    at ControlFlow.shutdown_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)
                    at shutdownTask_.MicroTask (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:31:2)
                    at addSpecsToSuite (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\sandeep\Desktop\Protractor\Protractor\specs\login_spec.js:4:1)
                    at Module._compile (module.js:570:32)
                    at Object.Module._extensions..js (module.js:579:10)
                    at Module.load (module.js:487:32)
                    at tryModuleLoad (module.js:446:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>