<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1521265718717' stop='1521265728279'>
    <name>To test the Angular binding functionality</name>
    <title>To test the Angular binding functionality</title>
    <test-cases>
        <test-case start='1521265718718' status='passed' stop='1521265722475'>
            <name>should not have any previous results</name>
            <title>should not have any previous results</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='5222f6f9-adfd-4f12-9801-9c68dbe5a4a8-attachment.png' type='image/png' size='15605'/>
            </attachments>
        </test-case>
        <test-case start='1521265722475' status='failed' stop='1521265725493'>
            <name>Should display calculation results for performed Arthematic operations and should save results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='72f4ffd8-cf46-4910-9218-0b6983c83fb4-attachment.png' type='image/png' size='18181'/>
            </attachments>
            <failure>
                <message>Expected 0 to equal 1.</message>
                <stack-trace>Error: Failed expectation
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\specs\calculation_spec.js:33:28
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at &lt;anonymous>
                    at process._tickCallback (internal/process/next_tick.js:118:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1521265725493' status='passed' stop='1521265728278'>
            <name>Should display calculation results for performed Arthematic operations and should save new results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save new results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='415db67c-873c-4862-a95d-043920bacd6e-attachment.png' type='image/png' size='18120'/>
            </attachments>
        </test-case>
    </test-cases>
</ns2:test-suite>